spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/litchi-admin?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      auto-commit: true
      pool-name: litchi_data_source_pool
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 60000
      idle-timeout: 50000
      connection-test-query: SELECT 1
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: litchi-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid

#springdoc相关配置
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'Litchi-Admin接口'
      paths-to-match: '/**'
      packages-to-scan: com.litchi    #按包路径匹配:一般到启动类的包名
#knife4j相关配置 可以不用改
knife4j:
  openapi:
    title: Litchi-Admin接口文档
    description: Litchi-Admin接口文档
    version: 1.0.0
    termsOfServiceUrl: https://www.gengby.com
    contact:
      name: Noah
      url: https://www.gengby.com
      email: gby_dev@163.com
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: 实体类   #重命名SwaggerModel名称,默认
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: Noah
    # Basic认证密码
    password: bing123




