server:
  port: 9999
  servlet:
    context-path: /litchi
spring:
  application:
    name: litchi
  profiles:
    active:
      - dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
